# Imports

In [2]:
import os
import pickle
import re
import shutil
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from itertools import product
from scipy.stats import norm
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yaml
from matplotlib.backends.backend_pdf import PdfPages
from tools import load_npy, load_yaml_as_df, load_pkl, exist_metric, exist_stf_metric, inverse_stf_metrics, keep_split, is_full_group, load_metric_from_log

plt.style.use('default')
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
plt.rc('font', family='Arial')
matplotlib.rcParams['mathtext.fontset'] = 'stix'
matplotlib.rcParams['font.size'] = 10

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Varying input length

## load data

In [3]:
root = '/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/ProjDF-Meta/results_ML3/vary_input'
exp_dirs = os.listdir(root)
exp_dirs = [os.path.join(root, exp_dir) for exp_dir in exp_dirs]

params = ['model', 'seq_len', 'pred_len', 'data_id', 'learning_rate', 'inner_lr', 'meta_lr', 'rec_lambda', 'auxi_lambda', 'reg_lambda', 'lradj', 'train_epochs', 'patience', 'batch_size', 'auxi_batch_size', 'warmup_steps', 'meta_inner_steps', 'overlap_ratio', 'num_tasks', 'max_norm', 'auxi_loss', 'first_order', 'dropout', 'cycle', 'task_name']
metric_names = ['mse', 'mae', 'cov']

df = []
for exp_dir in exp_dirs:
    runned, setting_dir = exist_metric(exp_dir)
    if not runned:
        continue

    config = load_yaml_as_df(os.path.join(setting_dir, 'config.yaml'))
    metric = load_npy(os.path.join(setting_dir, 'metrics.npy'))
    result = config[params]
    # if 'PatchTST' in exp_dir and 'all' in exp_dir and 'ml3' not in result['task_name']:
    #     shutil.rmtree(exp_dir)
    #     continue
    if len(metric) == 6:
        log_metrics = load_metric_from_log(os.path.join(exp_dir, 'result_long_term_forecast.txt'))
        cov_loss = log_metrics['cov'] if log_metrics and 'cov' in log_metrics else np.inf
        result.loc[:, metric_names] = metric[1], metric[0], cov_loss
    else:
        result.loc[:, metric_names] = metric[1], metric[0], metric[2]
    result.loc[:, ['meta_type']] = config[['meta_type']] if 'meta_type' in config.columns else 'all'
    result.loc[:, ['exp_dir']] = exp_dir
    df.append(result)

df = pd.concat(df, ignore_index=True)

df.sort_values(by=['model', 'data_id', 'seq_len', 'pred_len'], inplace=True)

save_root = '/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/ProjDF-Meta/stats_ML3'
os.makedirs(save_root, exist_ok=True)
df.to_csv(f"{save_root}/varying_input.csv", index=False)

df.head(4)

,model,seq_len,pred_len,data_id,learning_rate,inner_lr,meta_lr,rec_lambda,auxi_lambda,reg_lambda,lradj,train_epochs,patience,batch_size,auxi_batch_size,warmup_steps,meta_inner_steps,overlap_ratio,num_tasks,max_norm,auxi_loss,first_order,dropout,cycle,task_name,mse,mae,cov,meta_type,exp_dir
135,PatchTST,96,96,Weather,0.0002,0.0002,0.05,1.0,0.0,0.0,type1,3,3,32,64,300,1,0.0,3,5.0,MSE,1,0.1,24,long_term_forecast_meta_ml3,0.180137,0.223513,0.084849,all,/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/P...
136,PatchTST,96,96,Weather,0.0002,0.0002,0.10,1.0,0.0,0.0,type1,3,3,32,64,300,1,0.0,3,5.0,MSE,1,0.1,24,long_term_forecast_meta_ml3,0.181852,0.226392,0.068509,all,/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/P...
137,PatchTST,96,96,Weather,0.0002,0.0002,0.20,1.0,0.0,0.0,type1,3,3,32,64,300,1,0.0,3,5.0,MSE,1,0.1,24,long_term_forecast_meta_ml3,0.183564,0.228586,0.053923,all,/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/P...
138,PatchTST,96,96,Weather,0.0005,0.0005,0.05,1.0,0.0,0.0,type1,3,3,32,64,300,1,0.0,3,5.0,MSE,1,0.1,24,long_term_forecast_meta_ml3,0.186109,0.229123,0.087061,all,/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/P...

## preprocess

In [4]:
stats_root = '/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/ProjDF-Meta/stats_ML3'
log_root = '/mnt/tidalfs-bdsz01/usr/panlicheng/workspace/ProjDF-Meta/logs'
baselines = pd.read_csv(f'{log_root}/baselines_chosen.csv')
finetunes_best = pd.read_csv(f'{stats_root}/finetune_best.csv')

base = baselines.copy()
base = base[
    ((base.data_id == 'Weather') & (base.model.isin(['TQNet', 'PatchTST'])))
]
base['seq_len'] = 96
base['label'] = 'DF'

best = finetunes_best.copy()
best = best[
    ((best.data_id == 'Weather') & (best.model.isin(['TQNet', 'PatchTST'])))
]
best['seq_len'] = 96
best['label'] = 'QDF'


df2 = df.copy()
df2_base = df2[df2.task_name.apply(lambda x: 'ml3' not in x)].copy()
df2_base['label'] = 'DF'

df2 = df2[df2.task_name.apply(lambda x: 'ml3' in x)].copy()
df2['label'] = 'QDF'

min_mse_idx = df2.groupby(['model', 'data_id', 'seq_len', 'pred_len'])['mse'].idxmin()
df2 = df2.loc[min_mse_idx]

columns = ['model', 'data_id', 'seq_len', 'pred_len', 'label', 'mse', 'mae']
vary_seq = pd.concat([base[columns], df2_base[columns], best[columns], df2[columns]], ignore_index=True)
vary_seq['seq_len'] = vary_seq['seq_len'].astype(int)
vary_seq['pred_len'] = vary_seq['pred_len'].astype(int)

dst_order = ['Weather']
vary_seq['data_id'] = pd.Categorical(vary_seq['data_id'], categories=dst_order, ordered=True)

model_order = ['TQNet', 'PatchTST']
vary_seq['model'] = pd.Categorical(vary_seq['model'], categories=model_order, ordered=True)

label_order = ['QDF', 'DF']
vary_seq['label'] = pd.Categorical(vary_seq['label'], categories=label_order, ordered=True)

vary_seq_avg = vary_seq.groupby(['model', 'data_id', 'seq_len', 'label']).mean(numeric_only=True).reset_index()
vary_seq_avg['pred_len'] = 'Avg'
vary_seq = pd.concat([vary_seq, vary_seq_avg], ignore_index=True)

vary_seq.sort_values(by=['model', 'data_id', 'label', 'seq_len', 'pred_len'], inplace=True)

# save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
# vary_seq.round(3).to_csv(f'{save_root}/vary_seq.csv', index=False, float_format='%.3f')
vary_seq.dropna(inplace=True, thresh=6)
vary_seq

/tmp/ipykernel_1485149/1876595297.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  vary_seq_avg = vary_seq.groupby(['model', 'data_id', 'seq_len', 'label']).mean(numeric_only=True).reset_index()

       model  data_id  seq_len pred_len label       mse       mae
32     TQNet  Weather       96       96   QDF  0.158300  0.200693
33     TQNet  Weather       96      192   QDF  0.206637  0.244936
34     TQNet  Weather       96      336   QDF  0.262811  0.286290
35     TQNet  Weather       96      720   QDF  0.342250  0.339154
64     TQNet  Weather       96      Avg   QDF  0.242499  0.267768
52     TQNet  Weather      192       96   QDF  0.151933  0.199025
53     TQNet  Weather      192      192   QDF  0.197746  0.240933
54     TQNet  Weather      192      336   QDF  0.251799  0.281608
55     TQNet  Weather      192      720   QDF  0.324353  0.332215
66     TQNet  Weather      192      Avg   QDF  0.231458  0.263445
56     TQNet  Weather      336       96   QDF  0.148450  0.197914
57     TQNet  Weather      336      192   QDF  0.194562  0.239870
58     TQNet  Weather      336      336   QDF  0.244144  0.278709
59     TQNet  Weather      336      720   QDF  0.313122  0.327327
68     TQNet  Weather      336      Avg   QDF  0.225070  0.260955
60     TQNet  Weather      720       96   QDF  0.147805  0.198795
61     TQNet  Weather      720      192   QDF  0.192176  0.241383
62     TQNet  Weather      720      336   QDF  0.245771  0.284631
63     TQNet  Weather      720      720   QDF  0.310097  0.329413
70     TQNet  Weather      720      Avg   QDF  0.223962  0.263556
4      TQNet  Weather       96       96    DF  0.159965  0.202723
5      TQNet  Weather       96      192    DF  0.209872  0.247166
6      TQNet  Weather       96      336    DF  0.266696  0.288953
7      TQNet  Weather       96      720    DF  0.346121  0.342470
65     TQNet  Weather       96      Avg    DF  0.245663  0.270328
20     TQNet  Weather      192       96    DF  0.150983  0.197172
21     TQNet  Weather      192      192    DF  0.198130  0.241351
22     TQNet  Weather      192      336    DF  0.253357  0.282754
23     TQNet  Weather      192      720    DF  0.326561  0.334035
67     TQNet  Weather      192      Avg    DF  0.232258  0.263828
24     TQNet  Weather      336       96    DF  0.148850  0.198427
25     TQNet  Weather      336      192    DF  0.196287  0.242841
26     TQNet  Weather      336      336    DF  0.245528  0.280923
27     TQNet  Weather      336      720    DF  0.317805  0.331329
69     TQNet  Weather      336      Avg    DF  0.227118  0.263380
28     TQNet  Weather      720       96    DF  0.154551  0.206001
29     TQNet  Weather      720      192    DF  0.202892  0.251050
30     TQNet  Weather      720      336    DF  0.257349  0.294910
31     TQNet  Weather      720      720    DF  0.318849  0.338888
71     TQNet  Weather      720      Avg    DF  0.233410  0.272712
36  PatchTST  Weather       96       96   QDF  0.180137  0.223513
37  PatchTST  Weather       96      192   QDF  0.226342  0.262280
38  PatchTST  Weather       96      336   QDF  0.278642  0.300217
39  PatchTST  Weather       96      720   QDF  0.353759  0.347105
72  PatchTST  Weather       96      Avg   QDF  0.259720  0.283279
40  PatchTST  Weather      192       96   QDF  0.160677  0.208164
41  PatchTST  Weather      192      192   QDF  0.207125  0.247841
42  PatchTST  Weather      192      336   QDF  0.259073  0.286622
43  PatchTST  Weather      192      720   QDF  0.333628  0.337447
74  PatchTST  Weather      192      Avg   QDF  0.240126  0.270019
44  PatchTST  Weather      336       96   QDF  0.160348  0.213869
45  PatchTST  Weather      336      192   QDF  0.203817  0.252555
46  PatchTST  Weather      336      336   QDF  0.251373  0.286625
47  PatchTST  Weather      336      720   QDF  0.323754  0.338415
76  PatchTST  Weather      336      Avg   QDF  0.234823  0.272866
48  PatchTST  Weather      720       96   QDF  0.161154  0.216622
49  PatchTST  Weather      720      192   QDF  0.204846  0.255405
50  PatchTST  Weather      720      336   QDF  0.253819  0.292775
51  PatchTST  Weather      720      720   QDF  0.315484  0.337405
78  PatchTST  Weather      720      Avg   QDF  0.233826  0.275552
0   PatchTST  Weather       96       96    DF  0.188809  0.230401
1   PatchTST  Weather       96      192    DF  0.227930  0.261806
2   PatchTST  Weather       96      336    DF  0.288298  0.304599
3   PatchTST  Weather       96      720    DF  0.362152  0.353758
73  PatchTST  Weather       96      Avg    DF  0.266797  0.287641
8   PatchTST  Weather      192       96    DF  0.163353  0.208913
9   PatchTST  Weather      192      192    DF  0.207000  0.249358
10  PatchTST  Weather      192      336    DF  0.267826  0.293378
11  PatchTST  Weather      192      720    DF  0.510799  0.451114
75  PatchTST  Weather      192      Avg    DF  0.287245  0.300691
12  PatchTST  Weather      336       96    DF  0.157744  0.207817
13  PatchTST  Weather      336      192    DF  0.234973  0.290789
14  PatchTST  Weather      336      336    DF  0.251840  0.286720
15  PatchTST  Weather      336      720    DF  0.326002  0.335619
77  PatchTST  Weather      336      Avg    DF  0.242640  0.280236
16  PatchTST  Weather      720       96    DF  0.153189  0.205481
17  PatchTST  Weather      720      192    DF  0.204587  0.254277
18  PatchTST  Weather      720      336    DF  0.248264  0.288000
19  PatchTST  Weather      720      720    DF  0.317294  0.338599
79  PatchTST  Weather      720      Avg    DF  0.230833  0.271590

## write to table

In [5]:
contents = []


for sl in [96, 192, 336, 720]:
    line = r"& \multirow{5}{*}{" + str(sl) + r"}"
    contents.append(line)
    _df = vary_seq[vary_seq.seq_len == sl].copy().reset_index(drop=True)
    for pl in [96, 192, 336, 720, 'Avg']:
        line = f"& {pl} " if pl == 96 else f"&& {pl} "
        _dfp = _df[_df.pred_len == pl].copy().reset_index(drop=True)
        for model in ['TQNet', 'PatchTST']:
            _dfm = _dfp[_dfp.model == model].copy().reset_index(drop=True)
            for row in _dfm.itertuples():
                line += f"& {row.mse:.3f} & {row.mae:.3f} "
        line += r"\\"
        contents.append(line)
        if pl == 720:
            contents.append(r"\cmidrule(lr){3-11}")
    if sl != 720:
        contents.append(r"\cmidrule(lr){2-11}" + '\n')

print('\n'.join(contents))

& \multirow{5}{*}{96}
& 96 & 0.158 & 0.201 & 0.160 & 0.203 & 0.180 & 0.224 & 0.189 & 0.230 \\
&& 192 & 0.207 & 0.245 & 0.210 & 0.247 & 0.226 & 0.262 & 0.228 & 0.262 \\
&& 336 & 0.263 & 0.286 & 0.267 & 0.289 & 0.279 & 0.300 & 0.288 & 0.305 \\
&& 720 & 0.342 & 0.339 & 0.346 & 0.342 & 0.354 & 0.347 & 0.362 & 0.354 \\
\cmidrule(lr){3-11}
&& Avg & 0.242 & 0.268 & 0.246 & 0.270 & 0.260 & 0.283 & 0.267 & 0.288 \\
\cmidrule(lr){2-11}

& \multirow{5}{*}{192}
& 96 & 0.152 & 0.199 & 0.151 & 0.197 & 0.161 & 0.208 & 0.163 & 0.209 \\
&& 192 & 0.198 & 0.241 & 0.198 & 0.241 & 0.207 & 0.248 & 0.207 & 0.249 \\
&& 336 & 0.252 & 0.282 & 0.253 & 0.283 & 0.259 & 0.287 & 0.268 & 0.293 \\
&& 720 & 0.324 & 0.332 & 0.327 & 0.334 & 0.334 & 0.337 & 0.511 & 0.451 \\
\cmidrule(lr){3-11}
&& Avg & 0.231 & 0.263 & 0.232 & 0.264 & 0.240 & 0.270 & 0.287 & 0.301 \\
\cmidrule(lr){2-11}

& \multirow{5}{*}{336}
& 96 & 0.148 & 0.198 & 0.149 & 0.198 & 0.160 & 0.214 & 0.158 & 0.208 \\
&& 192 & 0.195 & 0.240 & 0.196 & 0.243 & 0.204 & 0.253 & 0.235 & 0.291 \\
&& 336 & 0.244 & 0.279 & 0.246 & 0.281 & 0.251 & 0.287 & 0.252 & 0.287 \\
&& 720 & 0.313 & 0.327 & 0.318 & 0.331 & 0.324 & 0.338 & 0.326 & 0.336 \\
\cmidrule(lr){3-11}
&& Avg & 0.225 & 0.261 & 0.227 & 0.263 & 0.235 & 0.273 & 0.243 & 0.280 \\
\cmidrule(lr){2-11}

& \multirow{5}{*}{720}
& 96 & 0.148 & 0.199 & 0.155 & 0.206 & 0.161 & 0.217 & 0.153 & 0.205 \\
&& 192 & 0.192 & 0.241 & 0.203 & 0.251 & 0.205 & 0.255 & 0.205 & 0.254 \\
&& 336 & 0.246 & 0.285 & 0.257 & 0.295 & 0.254 & 0.293 & 0.248 & 0.288 \\
&& 720 & 0.310 & 0.329 & 0.319 & 0.339 & 0.315 & 0.337 & 0.317 & 0.339 \\
\cmidrule(lr){3-11}
&& Avg & 0.224 & 0.264 & 0.233 & 0.273 & 0.234 & 0.276 & 0.231 & 0.272 \\